services:
  postgres:
    image: "ankane/pgvector:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vovk-ai-demo-db
    ports:
      - "5432:5432"
  redis:
    image: "redis:7.2-alpine"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
volumes:
  redis_data: